version: '3.8'

services:
  backend:
    build: .
    container_name: spam_detector_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app # Для разработки (hot-reload)
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - spam-network

  postgres:
    image: postgres:16-alpine
    container_name: spam_detector_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spam_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-spam_password}
      POSTGRES_DB: ${POSTGRES_DB:-spam_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-spam_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - spam-network

volumes:
  postgres_data:
    drive: local

networks:
  spam-network:
    driver: bridge
